### ISSUE TITLE
Issue in bcl-table component

### ISSUE THREAD

**Issue by vengador** [openeuropa/bootstrap-component-library#101]
Hi team, 

While I was working in UPD project, we have built one Drupal view with table format. In that view, one of the headers would allow users to sort table by that column but we found that link was not appearing in header. After a research, I found that problem is located in bcl-table component where it is rendering _cell.content for header cells (see https://github.com/openeuropa/bootstrap-component-library/blob/development/src/components/bcl-table/table.html.twig#L116). _cell.content stores only column name and pieces to build link is stored in another fields.
I have checked code in views-view-table.html.twig located in views module and we could replace:
`{{ _cell.content }}`
by
```
{%- if _cell.url -%}
  <a href="{{ _cell.url }}" title="{{ _cell.title }}" rel="nofollow">{{ _cell.content }}{{ _cell.sort_indicator }}</a>
{%- else -%}
  {{- _cell.content }}{{ _cell.sort_indicator }}
{%- endif -%}
``` 
I think that change in code could help us to make that Views functionality work. I hope this can be helpful.

**Comment by tibi2303** [comment]
Good day, I am not sure if you found already a way to resolve this but adding html markup inside _cell.content directly should provide the solution to this issue, in your case adding the html of the anchor inside that property. Please tell me if more information is needed or if it works this way. Thank you

**Comment by vengador** [comment]
Hi @tibi2303 
That could be a workaround, preprocessing _cell.content to contain HTML markup for link but if we have all those values ready in the template it could be rendered in that way that I suggest and we avoid extra work.

**Comment by tibi2303** [comment]
@vengador did you managed to do it this way?
