### ISSUE TITLE
Issue in bcl-breadcrumb

### ISSUE THREAD

**Issue by Joaoeduardoramos** [openeuropa/bootstrap-component-library#163]
Hello,

While I was working in EFSA project, after upgrading for D9 and oe_bootstrap_theme got this issue reported by acessibility tests:
 "Invalid state or property".
The breadcrumb aria-current attribute was added and its value is being double-encode.

https://github.com/openeuropa/bootstrap-component-library/blob/development/src/components/bcl-breadcrumb/breadcrumb.html.twig#L28

I suggest create and set atribute ie: 
`{% set _segment_attrs = create_attribute().setAttribute('aria-current','page') %}`
or use a "|raw" filter on
`{{ _segment_attrs|raw }}`
https://github.com/openeuropa/bootstrap-component-library/blob/development/src/components/bcl-breadcrumb/breadcrumb.html.twig#L32 .

Thank you!

João

**Comment by planctus** [comment]
Ops, the problem is evident. We will fix this in the next release. Since it's not foreseen to receive attributes from drupal about the single breadcrumb segments and we are just setting a single attribute, we will just use |raw as you suggested.
