### ISSUE TITLE
Turn the accordion items heading tag into a parameter

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/bootstrap-component-library#233]
### Description
In the [accordion template](https://github.com/openeuropa/bootstrap-component-library/blob/v0.18.0/src/components/bcl-accordion/accordion.html.twig), the items heading tag is hardcoded to be a h2.
This can a problem for some use cases because this component can be used nested the middle of a page (e.g. in a paragraph) and h2 may be too big. In our case, it's also a problem because we're using inpage navigation that is picking h2 headings but we don't want the accordion items to be shown there. A heading h3 would work much better.

### Proposed solution
I suggest to turn the heading tags of the items into parameters, so that they can be easily adapted for each case.

**Comment by planctus** [comment]
i agree, we can easily make the heading parametric as we have in many templates, `title_tag` will be added to keep this consistent, not sure about the usability of this new parameter in drupal without some work on the integration, though..

**Comment by planctus** [comment]
a jira ticket has been created for this, will close this issue once this is done.. ;)
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1071
