### ISSUE TITLE
Modal uses an "aria-labelledby" pointing to inexisting element

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/bootstrap-component-library#263]
### Description
In https://github.com/openeuropa/bootstrap-component-library/blob/v0.19.0/src/components/bcl-modal/modal.html.twig#L31
 ... the modal div gets the attribute "aria-labelledby" that does not exist.

This is not good and it will cause an error when in the [WAVE](https://wave.webaim.org/) report.

**Comment by planctus** [comment]
I agree that this attribute is misused here, it should probably simply be an aria-label, will open a ticket.
