### ISSUE TITLE
Content banner action_button should be a link that look like a button

### ISSUE THREAD

**Issue by msnassar** [openeuropa/bootstrap-component-library#334]
Problem:
The content banner composition has action_button parameter, which must be a button!
In most (might be all) cases, the action button will be a link that look like a button but not a button. As in the overview pages we do not do actions (submit, reset, ...)

**Comment by planctus** [comment]
![image](https://user-images.githubusercontent.com/14326885/164210483-9415abf4-6cf8-4ad4-8f47-c90a2767977c.png)

I see, we have no particular reason for choosing the button on our side, although this is probably how it was intended from the business analysis. We could make it optionally a link OR a button but I'm showing here the current status of the component (0.22) where there are two different areas for buttons, you are only interested in the action_button to be a link, right..?

**Comment by msnassar** [comment]
@planctus. Yes. for now I am interested in the action_button. But I think print and export should be links too.

**Comment by planctus** [comment]
The request is being considered, the result of this evaluation we are going to make will be reported here so that you know what is the decision ;)

**Comment by planctus** [comment]
Well, apparently for the bootstrap theme developers this whole area should be better defined as an "empty" block for them to feed it with already rendered markup. Would this approach suits you..? in this case we would not include any template only create room for you to "inject" the buttons or the links you want.

**Comment by planctus** [comment]
pr has been created, you can already take a look at it and confirm this is what we agreed upon.. ;)
https://github.com/openeuropa/bootstrap-component-library/pull/335

**Comment by planctus** [comment]
@msnassar , any feedback..? :)

**Comment by msnassar** [comment]
@planctus Thanks for the feedback. Sorry for late answer. I was on a holiday. 
I will have a look into it and try it out on UCPKN, when I have the time
