### ISSUE TITLE
Headings defaults not updated

### ISSUE THREAD

**Issue by dxvargas** [openeuropa/bootstrap-component-library#482]
Headings have been changing in some PRs.
In some cases the default value is not being updated.

I have these examples:

- h3 became h2 but `- title_tag: (string) (default: 'h3')` was not updated: https://github.com/openeuropa/bootstrap-component-library/pull/372/files#diff-1a7419db06a86ae7dbbf0d1c9f52eb0d9affa09a6b245d57716f76172510d787
- h5 became h1 but `- title_tag: (string) (default: 'h5')`was not updated: https://github.com/openeuropa/bootstrap-component-library/blob/v0.28.1/src/compositions/bcl-content-banner/content-banner.html.twig

This is a ticket for this to be fixed and a kind reminder for next heading updates, for the default value to be updated together :)

**Comment by tibi2303** [comment]
indeed, thanks for this, We already have an opened pr for updated documentation so I included them there.
