### ISSUE TITLE
Date block parameters in card template

### ISSUE THREAD

**Issue by msnassar** [openeuropa/bootstrap-component-library#484]
The date block template accepts the following parameters:
```
{#
  Parameters:
    - day (integer) (default: '')
    - month (string) (default: '')
    - date_time (string) (default: '')
    - year (integer) (default: '')
    - end_day (integer) (default: '')
    - end_month (string) (default: '')
    - end_year (integer) (default: '')
#}
```
See https://github.com/openeuropa/bootstrap-component-library/blob/development/src/compositions/bcl-date-block/date-block.html.twig

The date block template is included in the card template here: https://github.com/openeuropa/bootstrap-component-library/blob/development/src/components/bcl-card/card.html.twig#L154
passing to it one parameter: date 

```
{% include '@oe-bcl/bcl-date-block/date-block.html.twig' with _date only %}
```
How this supposed to work? Am I missing something?
Thanks

**Comment by tibi2303** [comment]
We use the card template also for the page banners which is supporting the date block, you can see an example here:
https://oelibrary.netlify.app/default/?path=/story/features-event--full-page-1

The date object that it's passed to the card template should include as props all the parameters that you mentioned:
`date: {
   day: 23,
   month: "June"
   year: "2022"
   etc...
}`

Indeed, maybe on our side should update the documentation but it is working as supossed

**Comment by tibi2303** [comment]
Feel free to close this ticket if everything is clear

**Comment by msnassar** [comment]
@tibi2303 Thanks for the feedback
Yes, It would be nice to update the documentation...
