### ISSUE TITLE
Inpage navigation is not working

### ISSUE THREAD

**Issue by bogdan24pop** [openeuropa/bootstrap-component-library#519]
After updating BCL from 0.24.1 to 1.0.0, inpage navigation 'active' class is not applied on the nav links. 
This can be seen also on netlify, for the [default](https://oelibrary.netlify.app/default/?path=/story/paragraphs-inpage-navigation--default) is working properly, but for [ucpkn](https://oelibrary.netlify.app/ucpkn/?path=/story/paragraphs-inpage-navigation--default) and [joinup](https://oelibrary.netlify.app/joinup/?path=/story/paragraphs-inpage-navigation--default) is not. 
This might be caused by the different versions of Scrollspy used.

**Comment by tibi2303** [comment]
We have update it and it's working in 1.0.2. This update only cover this thing
