### ISSUE TITLE
Image/media not displayed with multiple galleries on the same page

### ISSUE THREAD

**Issue by kp77** [openeuropa/bootstrap-component-library#527]
When more than one gallery is added to the page, only the first gallery is working correctly. The other galleries don't display the image/media in the modal/carousel when they are opened. BCL version: 1.0.2

The reason is that the image/iframe `data-src` attribute is not replaced with `src` attribute in case of the slides of the additional galleries. 

After debugging the script responsible for the replacement I found that in the [gallery.js ](https://github.com/openeuropa/bootstrap-component-library/blob/v1.0.2/src/themes/default/src/js/gallery/gallery.js#L45-L50)the selector context is incorrectly passed as `this.element` (which is undefined) in 3 places. The correct would be to pass: `element`. Because of the incorrect context, the Gallery instance is always using the first gallery's modal/carousel so this could also cause other issues.

To fix:

Line [45-46](https://github.com/openeuropa/bootstrap-component-library/blob/v1.0.2/src/themes/default/src/js/gallery/gallery.js#L45-L46) should be:
```js
    this.carousel = SelectorEngine.findOne(CAROUSEL_SELECTOR, element)
    this.carouselPager = SelectorEngine.findOne(CAROUSEL_PAGER_SELECTOR, element)
```
Line [50](https://github.com/openeuropa/bootstrap-component-library/blob/v1.0.2/src/themes/default/src/js/gallery/gallery.js#L50) should be:
```js
    this.modal = SelectorEngine.findOne(MODAL_SELECTOR, element)
```

**Comment by tibi2303** [comment]
indeed, thank you for reporting this. One small remark inside the pr and we can merge it.

**Comment by tibi2303** [comment]
@kp77 can we close this issue? the pr has been merged.

**Comment by kp77** [comment]
@tibi2303 Yes, it can be closed, thanks!
