### ISSUE TITLE
OEL-2771 : Gallery : Image fit

### ISSUE THREAD

**Issue by julien-** [openeuropa/bootstrap-component-library#564]
[OE Showcase](https://digit-oesa.acc.fpfis.tech.ec.europa.eu/en/patterns/gallery) uses ideal original 4:3 images but it is not reality.
Sample : in this [page](https://www.era.europa.eu/content/brazilian-delegation-era)

```patch
diff --git a/src/themes/default/src/scss/_gallery.scss b/src/themes/default/src/scss/_gallery.scss
index f4b915a5..7155757f 100644
--- a/src/themes/default/src/scss/_gallery.scss
+++ b/src/themes/default/src/scss/_gallery.scss
@@ -13,6 +13,11 @@
   .bcl-gallery__item {
     position: relative;
     cursor: pointer;
+    height: 100%;
+
+    img {
+      object-fit: cover;
+    }
   }
 
   .bcl-gallery__item-overlay {
```

![image](https://github.com/openeuropa/bootstrap-component-library/assets/7086610/294e10df-7cc3-44ab-af91-0a2890cc359b)
AFTER uses this [image](https://www.era.europa.eu/sites/default/files/2023-06/Brazilian%20Delegation%20at%20ERA%20-%201.JPG)

**Comment by brummbar** [comment]
The image passed to the gallery should be in format 4:3. From Drupal, formatters can be used to achieve it.
