### ISSUE TITLE
Preserve pagination list classes

### ISSUE THREAD

**Issue by msnassar** [openeuropa/bootstrap-component-library#565]
The classes for the pagination list passed by drupal are lost due to not allowing drupal to pass classes for the list https://github.com/openeuropa/bootstrap-component-library/blob/development/src/components/bcl-pagination/pagination.html.twig#L109.

Due to this, ajax on pagination is not working in drupal. The pagination requires "js-pager__items" class

**Comment by msnassar** [comment]
Here is a proposed solution
https://github.com/openeuropa/bootstrap-component-library/pull/566

**Comment by AaronGilMartinez** [comment]
Hi @msnassar closing this issue since is a duplicate, the issue will be fixed in oe_bootstrap_theme, thanks!
